version: '3.8'

services:
#  incident-api:
#    build:
#      context: .
#     container_name: incident-api
#     ports:
#       - "3000:3000"
#     depends_on:
#      - mongo

  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "27017:27017"
    volumes:
      - mongo_db:/data/mongo_db

volumes:
  mongo_db: